item {
  id: 1
  name: 'car'
}
item {
  id: 2
  name: 'motorbike'
}
item {
  id: 3
  name: 'person'
}
item {
  id: 4
  name: 'cat'
}
item {
  id: 5
  name: 'dog'
}
item {
  id: 6
  name: 'waterbottle'
}
item {
  id: 7
  name: 'chair'
}
item {
  id: 8
  name: 'table'
}
item {
  id: 9
  name: 'mobile'
}
item {
  id: 10
  name: 'laptop'
}


